mongodb:
  uri: 'mongodb://localhost:27017'
  dbname: 'owls_valley'
  connection:
    timeout: 1000

players-data:
  new-player:
    balance: 1500.50
  auto-save:
    enabled: true
    logging: true
    minutes: 1
